import React from "react";
import { Box, Typography, LinearProgress, Stack, Chip, Divider } from "@mui/material";
import useConditionStore from "../../../store/useConditionStore";
import useLayoutStore from "../../../store/useLayoutStore";

export default function ConditionEvaluation() {
  const { requirements } = useConditionStore();
  const { zones } = useLayoutStore();
  // TODO: `zoneSelections` is used for pptx/bottom bar picked items.
  // Actually, placed items may also come from `layoutItems` (which is generated by backend).
  // But wait, `AreaFurniturePanel` currently updates `zoneSelections` manually.
  // The backend generated `layoutItems` is drawn on canvas, but are they synced with `zoneSelections`?

  return (
    <Box sx={{ p: 2 }}>
      <Typography variant="h6" sx={{ fontWeight: "bold", mb: 2 }}>レイアウト評価</Typography>
      
      <Box sx={{ mb: 2 }}>
        <Typography variant="body2" color="text.secondary">条件達成率</Typography>
        <Stack direction="row" alignItems="center" spacing={1}>
          <Box sx={{ flex: 1 }}>
            <LinearProgress variant="determinate" value={80} color="success" sx={{ height: 8, borderRadius: 4 }} />
          </Box>
          <Typography variant="body2" fontWeight="bold">80%</Typography>
        </Stack>
      </Box>

      <Typography variant="subtitle2" sx={{ fontWeight: "bold", mt: 2, mb: 1 }}>必要数 / 配置数</Typography>
      
      <Stack spacing={1}>
        <EvalRow label="受付人数" req={requirements.receptionStaff} placed={0} />
        <EvalRow label="商談席数" req={requirements.meetingSeats} placed={0} />
        <EvalRow label="待合席数" req={requirements.waitingSeats} placed={0} />
        <EvalRow label="サービス待合席数" req={requirements.serviceWaitingSeats} placed={0} />
        <EvalRow label="事務席数" req={requirements.officeSeats} placed={0} />
      </Stack>

      <Typography variant="subtitle2" sx={{ fontWeight: "bold", mt: 3, mb: 1 }}>リア別配置アイテム数</Typography>
      <Stack spacing={1} sx={{ mb: 2 }}>
        {zones.length === 0 && <Typography variant="caption" color="text.secondary">ゾーニング未生成</Typography>}
        {zones.map((z) => {
          // Calculate placed items for this zone
          const relatedItems = useLayoutStore.getState().layoutItems.find(r => r.zone_id === z.id)?.items || [];
          return (
            <Box key={z.id} sx={{ display: "flex", justifyContent: "space-between" }}>
              <Typography variant="body2">{z.label || "未設定"}</Typography>
              <Typography variant="body2">{relatedItems.length} 個</Typography>
            </Box>
          );
        })}
      </Stack>

      <Divider sx={{ my: 2 }} />
      <Typography variant="subtitle2" fontWeight="bold" sx={{ mb: 1 }}>不足項目</Typography>
      <Stack direction="row" spacing={0.5} flexWrap="wrap">
        <Chip size="small" color="error" label="受付が未配置" sx={{ mb:0.5 }} />
        <Chip size="small" color="warning" label="商談席が-2席" sx={{ mb:0.5 }} />
      </Stack>

      <Typography variant="subtitle2" fontWeight="bold" sx={{ mt: 2, mb: 1 }}>案の特徴コメント</Typography>
      <Typography variant="body2" color="text.secondary">
        ・待合エリアを広めに確保<br />
        ・商談エリアを窓側に集中
      </Typography>
    </Box>
  );
}

function EvalRow({ label, req, placed }) {
  const r = Number(req) || 0;
  const p = Number(placed) || 0;
  if (r === 0 && p === 0) return null; // 両方0なら表示しない？いや、要件未入力時はどうする？
  // もし要件未入力でもとりあえず出す。
  
  const diff = p - r;
  const isOk = diff >= 0;
  return (
    <Box sx={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
      <Typography variant="body2" sx={{ width: 100 }}>{label}</Typography>
      <Typography variant="body2" fontWeight={isOk ? "bold" : "normal"} color={isOk ? "success.main" : "error.main"}>
        {p} / {r}
      </Typography>
    </Box>
  );
}
